### ISSUE TITLE
 Skeleton processing error

### ISSUE THREAD

**Issue by NightBaRron1412** [Nao974/choreograph-git#3]
I can't load Skeletons into the app

**Comment by Nao974** [comment]
Did you indicate the serial port in your skeleton? because there is currently no automatic search.
You can uncheck the Connect Controller, check motor and Update Engine options in the "Tools" -> Settings window. Then check the Verbose Log option. This will normally allow you to view the problem in the Terminal window.
![image](https://user-images.githubusercontent.com/7267005/123656853-5413f500-d841-11eb-8b25-69127b7a3edd.png)

**Comment by NightBaRron1412** [comment]
I guess that python can't find the path to my project file for some reason 
Here's what I got in the terminal.

![image](https://user-images.githubusercontent.com/17935216/123695013-559de700-d85a-11eb-850d-b5d04d981913.png)

**Comment by Nao974** [comment]
Yes, there is a path difference (absolute / relative) between launching from VsCode or live.
Have you tried to put the full path in "filepath" in the project file ?

**Comment by Nao974** [comment]
No more questions on the subject in 21 days, I consider it closed.
